services:
  - type: web
    name: paid-image-api
    runtime: node
    repo: https://github.com/cepuyut/paid-image-api.git
    branch: master
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: WALLET_PRIVATE_KEY
        sync: false
      - key: WALLET_ADDRESS
        value: "0xf48c6E46358652fC77462d56d609B8bC7f4ba82e"
      - key: CURRENCY_TOKEN
        value: "0x20c000000000000000000000b9537d11c60e8b50"
      - key: MPP_REALM
        value: pixelpay
      - key: MPP_CHALLENGE_SECRET
        sync: false
      - key: MPP_CHALLENGE_TTL
        value: "300"
      - key: TEMPO_CHAIN_ID
        value: "4217"
      - key: UPSTASH_REDIS_REST_URL
        sync: false
      - key: UPSTASH_REDIS_REST_TOKEN
        sync: false
