services:
  - type: web
    name: paid-image-api
    runtime: node
    repo: https://github.com/cepuyut/paid-image-api.git
    branch: master
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: FAL_KEY
        sync: false
      - key: WALLET_ADDRESS
        value: "0x8009c928c37285dc7e6e0527c3ac36d7a930e4eb"
      - key: CURRENCY_TOKEN
        value: "0x20c000000000000000000000b9537d11c60e8b50"
      - key: MPP_REALM
        value: pixelpay
      - key: MPP_CHALLENGE_SECRET
        sync: false
      - key: MPP_CHALLENGE_TTL
        value: "300"
      - key: TEMPO_CHAIN_ID
        value: "4217"
